import std/[strutils, strformat]
import commands

const parentDir: string = "completions/"

template completionZsh(list: untyped) =
    proc genZsh() =
        let
            dir: string = parentDir & "zsh/"
            fnName: string = "_" & PROGRAM
        var lines: seq[string] = @[
            "# Autogenerated with Nim script",
            "",
            &"compdef {fnName} {PROGRAM}",
            &"{fnName}() {"
        ]

        # Arguments:
        var args: seq[string]
        for item in list[]:
            var line: string
            # Flag names and description:
            case item.names.len():
            of 0: discard
            of 1: line &= item.names[0].getCommandFlagRepr()
            else:
                let commandNames: string = block:
                    var parts: seq[string]
                    for name in item.names:
                        parts.add name.getCommandFlagRepr()
                    parts.join(", ")

                line &= &"({commandNames})'<%{commandNames}%>'"
                line = line.replace("<%", "{").replace("%>", "}") # not in previous statement because it fucks the linter

            if line == "": continue
            line &= &"[{item.desc}]"

            # Types:
            if "file" in item.names: line &= ":dir:file:_files"
            if item.accepts.isSome():
                case item.accepts.get().argType:
                of $int: line &= ":number"
                else: discard
            args.add &"'{line}'"

        args.add "'*::file:_files'"

        lines.add "    _arguments \\"
        for arg in args:
            lines.add "        " & arg
        lines.add args.join(" \\\n").indent(8)

        lines.add "}"
        writeFile(dir & PROGRAM & ".zsh", lines.join("\n"))
    genZsh()


template generateTerminalCompletions*(list: untyped) =
    ## Generates completion files for some shells
    list.completionZsh()
